### ISSUE TITLE
Missing word in potential cost section 

### ISSUE THREAD

**Issue by wliao1** [iuctil/apred#152]
![image](https://user-images.githubusercontent.com/24637486/120546272-a63a3580-c3bd-11eb-8f2f-6b2cc4f80719.png)

@ljpaul what is the missing word?

**Comment by soichih** [comment]
@ljpaul FYI.. I am loading this text from `SELECT * FROM bea_gdp_uscnty_linecodes` *monthly*. Please let me know when I should reload it (or we can just wait for a month. :P )

**Comment by ljpaul** [comment]
This should say "social assistance"

**Comment by soichih** [comment]
From `db_stats4` db.

**Comment by soichih** [comment]
I've reloaded linecodes table. I see updated text now.
