### ISSUE TITLE
Potential cost data missing 

### ISSUE THREAD

**Issue by wliao1** [iuctil/apred#154]
Examples below: 

<img width="1173" alt="Screen Shot 2021-06-07 at 10 34 02 AM" src="https://user-images.githubusercontent.com/24637486/121035570-01807500-c77c-11eb-91d2-cfa74c5ab043.png">

<img width="1155" alt="Screen Shot 2021-06-07 at 10 34 43 AM" src="https://user-images.githubusercontent.com/24637486/121035591-07765600-c77c-11eb-9958-5c5883082301.png">

**Comment by soichih** [comment]
I forgot to rerun the backend ETL script after the update. I just did that and now I am seeing non-0 values.
