### ISSUE TITLE
Potential cost data not showing up for Rush, Indiana

### ISSUE THREAD

**Issue by wliao1** [iuctil/apred#156]
https://ctil.iu.edu/projects/apred/#/county/13237

<img width="1116" alt="Screen Shot 2021-06-07 at 5 15 20 PM" src="https://user-images.githubusercontent.com/24637486/121088591-fc3f1c80-c7b3-11eb-9c11-7e78cecd8d1f.png">

**Comment by ljpaul** [comment]
Both Putnam and Rush appear to now have data; we think this was just a loading issue.
