### ISSUE TITLE
Business Vulnerability Graphs Showing Zero

### ISSUE THREAD

**Issue by blj4** [iuctil/apred#60]
There are several instances where the business vulnerability graphs are showing zero when the data is actually null. For example, in Marion County, Indiana, it is showing zero employment for 2012-2014 in Agriculture, Forestry, Fishing and Hunting. However, the record is actually null in the database, which isn't the same as zero. In other words, there probably was employment - it just wasn't available in the County Business Patterns data from the Census Bureau. I'm not sure how you can show that in a line graph, other than take those points off the graph altogether. See image below for Marion County, Indiana.

![image](https://user-images.githubusercontent.com/73551173/97449656-48fe7300-1908-11eb-864d-98313c63885a.png)

**Comment by soichih** [comment]
We've switched to the bar graph so I think this is no longer an issue.

![image](https://user-images.githubusercontent.com/923896/112663564-5d9b5480-8e2f-11eb-868c-a122f105b818.png)

**Comment by blj4** [comment]
This does look better, but when you hover, it still says zero. Is there a way to note that it’s actually (D) instead of 0?

From: Soichi Hayashi ***@***.***>
Sent: Friday, March 26, 2021 12:33 PM
To: soichih/apred ***@***.***>
Cc: Hotchkiss, Brittany Lynn ***@***.***>; Author ***@***.***>
Subject: [External] Re: [soichih/apred] Business Vulnerability Graphs Showing Zero (#60)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


We've switched to the bar graph so I think this is no longer an issue.

[image]<https://user-images.githubusercontent.com/923896/112663564-5d9b5480-8e2f-11eb-868c-a122f105b818.png>

**Comment by iobik** [comment]
@soichih What do you think of the comment by @blj4?

**Comment by ljpaul** [comment]
I agree that if we can show a "D" instead of a zero it would be a little less misleading.

**Comment by iobik** [comment]
@soichih

**Comment by soichih** [comment]
@ljpaul I wasn't sure what you mean by D, but I've simply hidden the values (using null) if the value is less than or equal to 0. Here is what it looks like on dev.

![image](https://user-images.githubusercontent.com/923896/115094270-f5e69f80-9eea-11eb-8f18-44d4fd79b9f0.png)

**Comment by iobik** [comment]
Awesome! Thank you for the fixing the viz. 

@ljpaul @blj4 Does this look good to you?

**Comment by blj4** [comment]
When I hover, I am still seeing 0. When Logan said “D,” he means non-disclosable data. Since that’s not the same as zero, that’s why it’s misleading to show zero.

From: iobik ***@***.***>
Sent: Friday, April 16, 2021 7:37 PM
To: soichih/apred ***@***.***>
Cc: Hotchkiss, Brittany Lynn ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [soichih/apred] Business Vulnerability Graphs Showing Zero (#60)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


Awesome! Thank you for the fixing the viz.

@ljpaul<https://github.com/ljpaul> @blj4<https://github.com/blj4> Does this look good to you?

**Comment by soichih** [comment]
I just pushed the latest set of updates.

**Comment by blj4** [comment]
I definitely think you should get other opinions, but when I see that I feel like it means zero. I think it would be best if you allowed for zero to show and then ‘D’ to show if the data record is non-disclosable. That’s the most accurate way to display the data.

From: Soichi Hayashi ***@***.***>
Sent: Monday, April 19, 2021 10:44 AM
To: soichih/apred ***@***.***>
Cc: Hotchkiss, Brittany Lynn ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [soichih/apred] Business Vulnerability Graphs Showing Zero (#60)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.

I just pushed the latest set of updates.

**Comment by soichih** [comment]
Can you depict what you mean by "show D"? Can you draw something on a piece of paper and take a photo and upload it here? :)

**Comment by blj4** [comment]
What I’m imagining is that when you hover over a year with non-disclosable data, it will just say the letter D, instead of zero. And then a note can be added at the top or bottom that explains that ‘D’ means the data was non-disclosable. That way, users will see when it’s truly a zero and when it’s a non-disclosable data item.

***@***.***D73513.E8B7A840]

From: Soichi Hayashi ***@***.***>
Sent: Monday, April 19, 2021 11:40 AM
To: soichih/apred ***@***.***>
Cc: Hotchkiss, Brittany Lynn ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [soichih/apred] Business Vulnerability Graphs Showing Zero (#60)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


Can you depict what you mean by "show D"? Can you draw something on a piece of paper and take a photo and upload it here? :)

**Comment by ljpaul** [comment]
@soichih Please put a note at the top of the page (or the bottom) that states that there may be suppressed records included in this data, in which case it would be displayed as zero or none.

**Comment by blj4** [comment]
This denotes employment size class for data withheld to avoid disclosure (confidentiality) or withheld because data do not meet publication standards.


From: ljpaul ***@***.***>
Sent: Tuesday, April 27, 2021 2:02 PM
To: soichih/apred ***@***.***>
Cc: Hotchkiss, Brittany Lynn ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [soichih/apred] Business Vulnerability Graphs Showing Zero (#60)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


@soichih<https://github.com/soichih> Please put a note at the top of the page (or the bottom) that states that there may be suppressed records included in this data, in which case it would be displayed as zero or none.

**Comment by soichih** [comment]
We now have this label

![image](https://user-images.githubusercontent.com/923896/120377132-b8976f00-c2ea-11eb-9674-e87db79a2205.png)

Can we close this issue?

**Comment by blj4** [comment]
Yes, I think so.

From: Soichi Hayashi ***@***.***>
Sent: Tuesday, June 1, 2021 3:05 PM
To: iuctil/apred ***@***.***>
Cc: Hotchkiss, Brittany Lynn ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [iuctil/apred] Business Vulnerability Graphs Showing Zero (#60)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


We now have this label

[image]<https://user-images.githubusercontent.com/923896/120377132-b8976f00-c2ea-11eb-9674-e87db79a2205.png>

Can we close this issue?
